import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { 
  Dialog, 
  DialogContent, 
  DialogDescription, 
  DialogHeader, 
  DialogTitle, 
  DialogTrigger 
} from '@/components/ui/dialog';
import { 
  DropdownMenu, 
  DropdownMenuContent, 
  DropdownMenuItem, 
  DropdownMenuTrigger 
} from '@/components/ui/dropdown-menu';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { 
  Share2, 
  Download, 
  Check, 
  Copy,
  ChevronDown,
  FileText,
  Mail
} from 'lucide-react';
import type { SharedParams, Projector, CalculationResult } from '@/types';
import { AMBIENT_MULTIPLIERS } from '@/types';

interface ExportPanelProps {
  sharedParams: SharedParams;
  projectorA: Projector;
  projectorB: Projector;
  resultA: CalculationResult;
  resultB: CalculationResult;
}

export function ExportPanel({
  sharedParams,
  projectorA,
  projectorB,
  resultA,
  resultB,
}: ExportPanelProps) {
  const [copied, setCopied] = useState(false);
  const [shareUrl, setShareUrl] = useState('');

  const generateShareUrl = () => {
    const params = new URLSearchParams({
      screen: sharedParams.screenSize.toString(),
      throw: sharedParams.throwDistance.toString(),
      view: sharedParams.viewingDistance.toString(),
      ambient: sharedParams.ambientLight,
      nameA: projectorA.name,
      lumensA: projectorA.lumens.toString(),
      nameB: projectorB.name,
      lumensB: projectorB.lumens.toString(),
    });
    
    const url = `${window.location.origin}${window.location.pathname}?${params.toString()}`;
    setShareUrl(url);
    return url;
  };

  const copyToClipboard = async () => {
    const url = shareUrl || generateShareUrl();
    try {
      await navigator.clipboard.writeText(url);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const exportAsText = () => {
    const ambientLabel = AMBIENT_MULTIPLIERS[sharedParams.ambientLight].label;
    
    const text = `
Projector Brightness Comparison - ProjSim
==========================================

SETUP
-----
Screen Size: ${sharedParams.screenSize} inches
Throw Distance: ${sharedParams.throwDistance} ft
Viewing Distance: ${sharedParams.viewingDistance} ft
Ambient Light: ${ambientLabel}

PROJECTOR A: ${projectorA.name}
-------------------------------
Brightness: ${projectorA.lumens.toLocaleString()} lumens
Foot-Lamberts: ${resultA.footLamberts.toFixed(1)} fL
Nits: ${resultA.nits.toFixed(1)} cd/m²
Rating: ${resultA.rating}
Visual Brightness: ${Math.round(resultA.visualBrightness)}%

PROJECTOR B: ${projectorB.name}
-------------------------------
Brightness: ${projectorB.lumens.toLocaleString()} lumens
Foot-Lamberts: ${resultB.footLamberts.toFixed(1)} fL
Nits: ${resultB.nits.toFixed(1)} cd/m²
Rating: ${resultB.rating}
Visual Brightness: ${Math.round(resultB.visualBrightness)}%

COMPARISON
----------
Brightness Difference: ${Math.abs(resultB.footLamberts - resultA.footLamberts).toFixed(1)} fL
Winner: ${resultB.footLamberts > resultA.footLamberts ? projectorB.name : projectorA.name}

Generated by ProjSim - Projector Brightness Simulator
    `.trim();

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'projector-comparison.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const shareViaEmail = () => {
    const ambientLabel = AMBIENT_MULTIPLIERS[sharedParams.ambientLight].label;
    const winner = resultB.footLamberts > resultA.footLamberts ? projectorB.name : projectorA.name;
    
    const subject = encodeURIComponent('Projector Brightness Comparison - ProjSim');
    const body = encodeURIComponent(`
Check out this projector comparison:

Setup: ${sharedParams.screenSize}" screen, ${ambientLabel}

${projectorA.name}: ${resultA.footLamberts.toFixed(1)} fL (${resultA.rating})
${projectorB.name}: ${resultB.footLamberts.toFixed(1)} fL (${resultB.rating})

Winner: ${winner}

View full comparison: ${shareUrl || generateShareUrl()}
    `.trim());
    
    window.open(`mailto:?subject=${subject}&body=${body}`);
  };

  return (
    <div className="flex items-center gap-2">
      <Dialog>
        <DialogTrigger asChild>
          <Button variant="outline" size="sm" className="flex items-center gap-2">
            <Share2 className="w-4 h-4" />
            <span className="hidden sm:inline">Share</span>
          </Button>
        </DialogTrigger>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Share2 className="w-5 h-5" />
              Share Comparison
            </DialogTitle>
            <DialogDescription>
              Share this projector comparison with others.
            </DialogDescription>
          </DialogHeader>
          
          <div className="space-y-4 mt-4">
            {/* Copy Link */}
            <div className="space-y-2">
              <Label>Share Link</Label>
              <div className="flex gap-2">
                <Input 
                  value={shareUrl || generateShareUrl()} 
                  readOnly 
                  className="flex-1 text-sm"
                  onClick={(e) => e.currentTarget.select()}
                />
                <Button 
                  onClick={copyToClipboard}
                  variant={copied ? 'default' : 'outline'}
                  className={copied ? 'bg-green-600 hover:bg-green-700' : ''}
                >
                  {copied ? (
                    <Check className="w-4 h-4" />
                  ) : (
                    <Copy className="w-4 h-4" />
                  )}
                </Button>
              </div>
              {copied && (
                <p className="text-xs text-green-600">Link copied to clipboard!</p>
              )}
            </div>

            {/* Export Options */}
            <div className="space-y-2">
              <Label>Export</Label>
              <div className="grid grid-cols-2 gap-2">
                <Button 
                  variant="outline" 
                  onClick={exportAsText}
                  className="flex items-center gap-2"
                >
                  <FileText className="w-4 h-4" />
                  Export as Text
                </Button>
                <Button 
                  variant="outline" 
                  onClick={shareViaEmail}
                  className="flex items-center gap-2"
                >
                  <Mail className="w-4 h-4" />
                  Email
                </Button>
              </div>
            </div>

            {/* Summary */}
            <div className="p-3 bg-slate-50 rounded-lg border border-slate-200">
              <h4 className="text-sm font-medium text-slate-700 mb-2">Comparison Summary</h4>
              <div className="space-y-1 text-xs">
                <div className="flex justify-between">
                  <span className="text-slate-500">Screen:</span>
                  <span className="font-medium">{sharedParams.screenSize}"</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Ambient:</span>
                  <span className="font-medium">{AMBIENT_MULTIPLIERS[sharedParams.ambientLight].label}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">{projectorA.name}:</span>
                  <span className="font-medium">{resultA.footLamberts.toFixed(1)} fL</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">{projectorB.name}:</span>
                  <span className="font-medium">{resultB.footLamberts.toFixed(1)} fL</span>
                </div>
              </div>
            </div>
          </div>
        </DialogContent>
      </Dialog>

      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant="outline" size="sm" className="flex items-center gap-1">
            <Download className="w-4 h-4" />
            <ChevronDown className="w-3 h-3" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          <DropdownMenuItem onClick={exportAsText}>
            <FileText className="w-4 h-4 mr-2" />
            Export as Text
          </DropdownMenuItem>
          <DropdownMenuItem onClick={shareViaEmail}>
            <Mail className="w-4 h-4 mr-2" />
            Share via Email
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  );
}
